apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-be-deployment
  namespace: msa-be
spec:
  selector:
    matchLabels:
      app: msa-be
  replicas: 2
  template:
    metadata:
      labels:
        app: msa-be
    spec:
      containers:
      - name: msa-be
        image: nghia2742/msa-be:d7e9e42a3e621db5daa659e8f7501a8f76f08af9
        ports:
        - containerPort: 5000
