apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: msa-fe-stage
resources:
- ../../base
nameSuffix: -stage
labels:
- includeSelectors: true
  pairs:
    env: stage
images:
- name: nghia2742/msa-fe
  newName: nghia2742/msa-fe
  newTag: ab008bd31f77bcfd37b279ddc07704074731849c

configMapGenerator:
- name: msa-fe-config
  literals:
  - NEXT_PUBLIC_ENVIRONMENT=stage
  - NEXT_PUBLIC_BFF_ENDPOINT=http://msa-bff-service-stage.msa-bff-stage.svc.cluster.local:4000/bff
