apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: msa-fe-stage
resources:
- ../../base
nameSuffix: -stage
commonLabels:
  env: stage
images:
- name: nghia2742/msa-fe
  newName: nghia2742/msa-fe
  newTag: ab008bd31f77bcfd37b279ddc07704074731849c
