apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msa-bff
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nghia2742/msa-config.git
    targetRevision: HEAD
    path: k8s/msa-bff
  destination: 
    server: https://kubernetes.default.svc
    namespace: msa-bff
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true