apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -stage
commonLabels:
  env: stage
images:
- name: nghia2742/msa-bff
  newName: nghia2742/msa-bff
  newTag: 989e4c86556024336c02d9acbf8da53cc26fae07
