apiVersion: v1
kind: Service
metadata:
  name: msa-bff-service
  namespace: msa-bff
spec:
  selector:
    app: msa-bff
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  type: ClusterIP
