apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-fe
  namespace: default
spec:
  selector:
    matchLabels:
      app: msa-fe
  replicas: 2
  template:
    metadata:
      labels:
        app: msa-fe
    spec:
      containers:
      - name: msa-fe
        image: nghia2742/msa-fe:4e98609afb61446d61f1426e811b9c4ae0f9ebbc
        ports:
        - containerPort: 3000