apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-fe-deployment
  namespace: msa-fe
spec:
  selector:
    matchLabels:
      app: msa-fe
  replicas: 2
  template:
    metadata:
      labels:
        app: msa-fe
    spec:
      containers:
      - name: msa-fe
        image: nghia2742/msa-fe:08447f4d2b6d0969165ceb4764ef4fdc62e2be5c
        ports:
        - containerPort: 3000