apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -dev
commonLabels:
  env: dev
images:
- name: nghia2742/msa-be
  newName: nghia2742/msa-be
  newTag: c67fae2dd534b4f1d2dfad824cb9addcf91b6979
