apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -dev
commonLabels:
  env: dev
images:
- name: nghia2742/msa-be
  newName: nghia2742/msa-be
  newTag: 00c678c544f6f90855f2395766bbc7eaf9ac4507
