apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: msa-be-dev
resources:
- ../../base
nameSuffix: -dev
commonLabels:
  env: dev
images:
- name: nghia2742/msa-be
  newName: nghia2742/msa-be
  newTag: 94b026148e9912350101fe89f606550edc867c6d
