apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: msa-fe-prod
resources:
- ../../base
nameSuffix: -prod
labels:
- includeSelectors: true
  pairs:
    env: prod
patches:
- target:
    kind: Deployment
    name: msa-fe-deployment
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3

configMapGenerator:
- name: msa-fe-config
  literals:
  - NEXT_PUBLIC_ENVIRONMENT=production
  - NEXT_PUBLIC_BFF_ENDPOINT=https://api.msa.com/bff # Giả sử endpoint production
