apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: msa-fe-prod
resources:
- ../../base
nameSuffix: -prod
commonLabels:
  env: prod
patches:
- target:
    kind: Deployment
    name: msa-fe-deployment
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
