apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: msa-fe-dev
resources:
- ../../base
nameSuffix: -dev
commonLabels:
  env: dev
images:
- name: nghia2742/msa-fe
  newName: nghia2742/msa-fe
  newTag: ecdf60c6b0de5926256f61100d2db634f0b35392
