apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: msa-fe-dev
resources:
- ../../base
nameSuffix: -dev
commonLabels:
  env: dev
images:
- name: nghia2742/msa-fe
  newName: nghia2742/msa-fe
  newTag: e6fa4748b7024c6cb7294e6878d723c696cfcd4c

configMapGenerator:
- name: msa-fe-config
  literals:
  - NEXT_PUBLIC_ENVIRONMENT=development
  - NEXT_PUBLIC_BFF_ENDPOINT=http://msa-bff-service-dev:4000/bff
